"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:black)\
$os\
[](bg:purple fg:black)\
$username$hostname\
[](fg:purple bg:black)\
$git_branch$git_status$docker_context\
[](fg:black bg:bright-black)\
$nodejs$rust$golang$php$c$cpp$zig$lua$ocaml$python$cmake\
[](fg:bright-black)\
\n$directory\
\n$sudo$character\
"""

right_format = """$cmd_duration"""

[cmd_duration]
disabled = false
style = "fg:bright-black"
format = "[]($style)[ $duration](bg:bright-black fg:bright-white)[]($style)"

[username]
show_always = true
style_root = "bg:red fg:bright-white"
style_user = "bg:purple fg:black"
format = "[$user]($style)"

[character]
success_symbol = "[󰇼](bold green)"
error_symbol = "[󰇼](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_replace_symbol = "[](bold bright-purple)"
vimcmd_replace_one_symbol = "[](bold bright-purple)"
vimcmd_visual_symbol = "[](bold yellow)"

[directory]
style = "fg:black"
format = "[]($style)[$path](bg:black fg:bright-white)[]($style)"
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"~" = ""
".config" = ""
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Dev" = ""
"ai" = ""
"c" = ""
"cpp" = ""
"c3c" = ""
"github" = "󰊤"
"go" = ""
"godot" = ""
"java" = ""
"js" = ""
"lua" = ""
"nasm" = "󱄔"
"ocaml" = ""
"odin" = ""
"python" = ""
"rust" = ""
"sh" = ""
"zig" = ""

[hostname]
ssh_symbol = " "
style = "bg:purple fg:black"
format = "[ $ssh_symbol$hostname]($style)"
# uncomment to always show
# ssh_only = false
disabled = false

[git_branch]
symbol = ""
style = "bg:black"
format = '[[ $symbol $branch ](fg:bright-purple bg:black)]($style)'

[git_status]
ignore_submodules = false
style = "bg:black"
format = '[[($all_status$ahead_behind )](fg:bright-purple bg:black)]($style)'
conflicted = "󰦎"
ahead = "󰮽"
behind = "󰮷"
diverged = "󰃻"
up_to_date = ""
untracked = ""
stashed = "󰀼"
modified = ""
staged = ""
renamed = "󰑕"
deleted = "󰛌"
typechanged = "󱎋"

[lua]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'

[ocaml]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'

[c]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'

[cpp]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'

[cmake]
symbol = "| "
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'
detect_files = ['CMakeLists.txt', 'CMakeCache.txt', 'makefile', 'Makefile']

[python]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'

[zig]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:bright-purple bg:#212736)]($style)'

[docker_context]
symbol = " "

[os]
format = '[$symbol](bg:black fg:white)'
disabled = false

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CachyOS = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
Nobara = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"
