format = """
[](#a3aed2)\
$os\
[](bg:#769ff0 fg:#a3aed2)\
$hostname\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$docker_context\
$nodejs\
$rust\
$golang\
$php\
$c\
$cpp\
$zig\
$lua\
$ocaml\
$python\
[](fg:#394260 bg:#212736)\
$cmake\
[](fg:#212736 bg:#1d2230)\
[](fg:#1d2230)\
\
\n[](fg:#1d2230)\
$directory\
[](fg:#1d2230)\
\
\n$sudo$character\
"""

right_format = """
[](#a3aed2)\
$time\
[](fg:#a3aed2)\
"""

[character]
success_symbol = "[󰇼](bold green)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_visual_symbol = "[](bold yellow)"

[directory]
style = "fg:#e3e5e5 bg:#1d2230"
format = "[$path ]($style)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
".config" = ""
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[hostname]
ssh_symbol = " "
style = "bg:#769ff0 fg:#394260"
format = "[ $ssh_symbol$hostname]($style)"
# uncomment to always show
# ssh_only = false
disabled = false

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#a3aed2"
format = '[[ $time](bg:#a0a9cb fg:#1d2230)]($style)'

[lua]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[ocaml]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[c]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[cpp]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[cmake]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[zig]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[docker_context]
symbol = " "

[os]
format = '[$symbol](fg:#212736 bg:#a3aed2)'
disabled = false

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CachyOS = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
Nobara = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"
