"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:bright-black)\
$os\
[](bg:purple fg:bright-black)\
$hostname\
[](fg:purple bg:#394260)\
$git_branch$git_status$docker_context\
[](fg:#394260 bg:bright-black)\
$nodejs$rust$golang$php$c$cpp$zig$lua$ocaml$python$cmake\
[](fg:bright-black)\
\n[](fg:#1d2230)\
$directory\
[](fg:#1d2230)\
\n$sudo$character\
"""

right_format = """[](bright-black)\
$time\
[](fg:bright-black)"""

[character]
success_symbol = "[󰇼](bold green)"
error_symbol = "[󰇼](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_visual_symbol = "[](bold yellow)"

[directory]
style = "fg:bright-white bg:bright-black"
format = "[$path]($style)"
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
".config" = ""
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[hostname]
ssh_symbol = " "
style = "bg:purple fg:bright-black"
format = "[ $ssh_symbol$hostname]($style)"
# uncomment to always show
# ssh_only = false
disabled = false

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:purple bg:#394260)]($style)'

[git_status]
ignore_submodules = false
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:purple bg:#394260)]($style)'
conflicted = "󰦎"
ahead = "󰮽"
behind = "󰮷"
diverged = "󰃻"
up_to_date = ""
untracked = ""
stashed = "󰀼"
modified = ""
staged = ""
renamed = "󰑕"
deleted = "󰛌"
typechanged = "󱎋"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:bright-black"
format = '[[ $time](bg:bright-black fg:bright-white)]($style)'

[lua]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'

[ocaml]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'

[c]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'

[cpp]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'

[cmake]
symbol = "| "
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'
detect_files = ['CMakeLists.txt', 'CMakeCache.txt', 'makefile', 'Makefile']

[python]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'

[zig]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:purple bg:#212736)]($style)'

[docker_context]
symbol = " "

[os]
format = '[$symbol](bg:bright-black fg:white)'
disabled = false

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CachyOS = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
Nobara = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"
